#ifndef __MAIN_INC_ETH_SERVICE_H__
#define __MAIN_INC_ETH_SERVICE_H__

// #define USE_ETH_STATIC_IP

#define CONFIG_EXAMPLE_ETH_PHY_IP101 1
#define CONFIG_EXAMPLE_USE_INTERNAL_ETHERNET 1
#define CONFIG_EXAMPLE_ETH_PHY_RST_GPIO 5
#define CONFIG_EXAMPLE_ETH_MDIO_GPIO 18
#define CONFIG_EXAMPLE_ETH_MDC_GPIO 23
#define CONFIG_EXAMPLE_ETH_PHY_ADDR 1

void initialise_eth(void);

#endif // __MAIN_INC_ETH_SERVICE_H__